{application,game,
             [{description,[]},
              {vsn,"1"},
              {registered,[game_sup]},
              {applications,[kernel,stdlib]},
              {mod,{game_app,[]}},
              {env,[]},
              {modules,[bullet,game,game_app,game_logic,game_serializer,
                        game_server,game_sup,player]}]}.
